name: Code Coverage Reporter
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 2,14 * * *'

  pull_request:


jobs:
  build_and_analysis:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare Corfu
        run: .ci/infrastructure-docker-build.sh docker
        shell: bash

      - name: run integration tests
        run: ./mvnw clean verify -P codecov

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/target/site/jacoco-aggregate/jacoco.xml

      - name: Upload Codecov report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/target/site/jacoco-aggregate/jacoco.xml